### ISSUE TITLE
Subcolums value error

### ISSUE THREAD

**Issue by hot2dev** [contao-community-alliance/composer-client#245]
Hey there,
i just added the composer client into the backend.
Now all my articles with subcolums are on default, the percent width is removed.
Is this normal ore is there any problem right now?
Best regards

**Comment by hot2dev** [comment]
contao 3.3.6

**Comment by kikmedia** [comment]
Well, this could happen if you made an update of the subcolumns extension since the code of the ER versions (where we've got the last update at 11.08.2013) differ from the code via github (which has been updated for the last time in November 2014).

In my opinion, this is not a composer-client related bug.

**Comment by discordier** [comment]
It could also be that you have not yet finished the migration yet and therefore need to install the extension. What happens when you click on the test run button in the package manager?
